//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int AdminID { get; set; }
        public int UserID { get; set; }
        public System.DateTime AcountExpire { get; set; }
        public Nullable<int> AdminTypeID { get; set; }
    
        public virtual tblAdminType tblAdminType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
