//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploye
    {
        public int EmployeID { get; set; }
        public int UserID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<double> Salary { get; set; }
        public int ExperienceYear { get; set; }
        public int EducationID { get; set; }
        public int ManagerID { get; set; }
    
        public virtual tblEducation tblEducation { get; set; }
        //public virtual tblEmploye tblManager { get; set; }
        public virtual tblManager tblManager { get; set; }
        
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
