//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblManager()
        {
            this.tblEmployes = new HashSet<tblEmploye>();
           
        }
    
        public int ManagerID { get; set; }
        public int UserID { get; set; }
        public string Mail { get; set; }
        public string HelpPass { get; set; }
        public Nullable<int> DutyLevel { get; set; }
        public Nullable<int> ProjectsDone { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmploye> tblEmployes { get; set; }       
        public virtual tblUser tblUser { get; set; }
    }
}
