//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportID { get; set; }
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string WorkDesc { get; set; }
        public int TotalHours { get; set; }
    }
}
