//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmploye
    {
        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string JMBG { get; set; }
        public int GenderID { get; set; }
        public string Place { get; set; }
        public int MariageID { get; set; }
        public string Username { get; set; }
        public string Pasword { get; set; }
        public int ExperienceYear { get; set; }
        public Nullable<double> Salary { get; set; }
        public int EducationID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public int ManagerID { get; set; }
        public int EmployeID { get; set; }
    }
}
